### PR TITLE
Removed old Arctic projection layers

### PR DESCRIPTION
**Pull request by minniewong**
Partially closes nasa-gibs/worldview#738

Removed arctic_coastline.json, arctic_graticule.json, arctic_coastlines.md and removed layers from layerOrder.jsno

### CODE REVIEW

**Comment by Benjaki2** [comment]
@minniewong though it won't really affect the code, https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/features.json#L10 can be removed from the features as well.

**Comment by minniewong** [comment]
@Benjaki2 - Thanks! I've removed that tag.

**Comment by Benjaki2** [comment]
Nice! @minniewong 
nasa-gibs/worldview#834 just needs to be reviewed/approved. It should be ready to go into `develop` tomorrow.

**Pull request merged**
