### PR TITLE
Added JSON Linting + Travis CI integration

### PR DESCRIPTION
**Pull request by ZachTRice**
Connects to #104

### CODE REVIEW

**Comment by ZachTRice** [comment]
When we merge this PR, let's delete the `2.0.0` tag in place now; then create a proper `2.0.0` release; this will regenerate that tag. From here on out we will start properly versioning / releasing option repo changes. This [WV PR](https://github.com/nasa-gibs/worldview/pull/517) will start looking for the options version tag within WV.

**Comment by Benjaki2** [comment]
@ZachTRice I've tried to delete tags in the past and I have had trouble. I would say just go with `2.1.0` unless you find clean way to remove a tag without excessive `--force`

**Comment by ZachTRice** [comment]
I just removed it so we should be good to go. I think they have made the process a bit easier. If you remove a release it leaves just a tag; you can then go in to edit a tag and delete it. It gets rid of any reference to the release / tag. So, it's back to a clean slate now. Just make sure to merge this before the [Default Options Repo in Worldview PR](https://github.com/nasa-gibs/worldview/pull/517)

**Comment by localjo** [comment]
There are still conflicts on this branch.

screen shot 2017-11-29 at 11 58 24 am

**Pull request merged**
